repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      # Run the formatter first.
      - id: ruff-format
      # Then lint the already-formatted code.
      - id: ruff
        args: [--fix]