blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/JacksonFergusonDev/star-ground/discussions
    about: Please ask questions or discuss ideas here before opening an issue.